### ISSUE TITLE
PHP8 support - Fatal error: Uncaught Error: call_user_func_array(): Argument #1 ($function) must be a valid callback, function "auto_update_woocommerce" not found or invalid function name

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-beta-tester#78] opened 2020-11-03 00:17 UTC
I'm trying to use WooCommerce Beta Tester to update to WooCommerce 4.7+. I'm using VVV and running on PHP8.

With WooCommerce Beta Tester active, when I view the wp-admin/plugins page I get this error:

`Fatal error: Uncaught Error: call_user_func_array(): Argument #1 ($function) must be a valid callback, function "auto_update_woocommerce" not found or invalid function name in /srv/www/wordpress-two/public_html/wp-includes/class-wp-hook.php on line 287`

If I deactivate WooCommerce Beta Tester, the plugins page loads fine. (I'm using [VVV's wp-cli](https://varyingvagrantvagrants.org/docs/en-US/references/wp-cli/) to deactivate.)

Apologies if this is not a beta tester issue, I don't have a lot of experience with VVV and PHP8 so this might be caused by something else.

**Comment by rrennick** [comment] 2020-11-03 01:11
Duplicate of https://github.com/woocommerce/woocommerce-beta-tester/issues/69. 

@haszari The issue is fixed in master.

**Closed as completed by rrennick** 2020-11-03 01:11 UTC
